# Values used for the deployed application.
replicaCount: 2
service:
  name: locations-smartlogic-notifier
config:
  smartlogicModelKey: "smartlogic.locations.model"
  logLevel: INFO
  kafkaTopic: SmartlogicConcept
  conceptUriPrefix: "http://www.ft.com/ontology/managedlocation/"
  smartlogicHealthcheckConcept: "822e3c99-afc6-3c55-b497-2255ac546f35"
